name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull saptarshi2446/cicd-pipeline-second:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-second-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8083:8081 --name cicd-pipeline-second-container saptarshi2446/cicd-pipeline-second
    - name: Check Docker Container
      run: sudo docker ps -a