name: EC2 Script Deploy and OS Check with multi Job

on: push

jobs:
  add-host:
    runs-on: self-hosted
    steps:
      - name: Checkout repo (fetch python script)
        uses: actions/checkout@v3

      - name: Add host via API Python script for each pair
        env:
          REMOTE_IPS: ${{ secrets.REMOTE_IPS }}
          SCRIPT_LOCAL_PYTHON: zabbix_host_add.py
        run: |
          IFS=',' read -ra HOST_PAIRS <<< "$REMOTE_IPS"
          for PAIR in "${HOST_PAIRS[@]}"; do
            REMOTE_IP="${PAIR%%:*}"
            REMOTE_HOSTNAME="${PAIR#*:}"

            echo "Adding host $REMOTE_HOSTNAME with IP $REMOTE_IP..."
            python3 "$SCRIPT_LOCAL_PYTHON" "$REMOTE_IP" "$REMOTE_HOSTNAME"
          done

  add-agent:
    runs-on: self-hosted
    steps:
      - name: Checkout repo (fetch PEM and scripts)
        uses: actions/checkout@v3

      - name: Secure PEM file
        run: chmod 600 zbx_srv1.pem

      - name: Run commands and deploy agent script on EC2
        env:
          REMOTE_IPS: ${{ secrets.REMOTE_IPS }}
          PEM_FILE: zbx_srv1.pem
          REMOTE_USER: ubuntu
          SCRIPT_LOCAL: zabbix_agent_add.sh
          SCRIPT_REMOTE: /home/ubuntu/zabbix_agent_add.sh
        run: |
          IFS=',' read -ra HOST_PAIRS <<< "$REMOTE_IPS"
          for PAIR in "${HOST_PAIRS[@]}"; do
            REMOTE_IP="${PAIR%%:*}"
            REMOTE_HOSTNAME="${PAIR#*:}"

            echo "--- $REMOTE_IP ($REMOTE_HOSTNAME): OS Version ---"
            ssh -o StrictHostKeyChecking=no -i "$PEM_FILE" "$REMOTE_USER@$REMOTE_IP" "cat /etc/os-release"

            echo "📦 Copying $SCRIPT_LOCAL to $REMOTE_USER@$REMOTE_IP ..."
            scp -o StrictHostKeyChecking=no -i "$PEM_FILE" "$SCRIPT_LOCAL" "$REMOTE_USER@$REMOTE_IP:$SCRIPT_REMOTE"

            echo "🚀 Executing agent script on $REMOTE_USER@$REMOTE_IP ..."
            ssh -o StrictHostKeyChecking=no -i "$PEM_FILE" "$REMOTE_USER@$REMOTE_IP" "bash $SCRIPT_REMOTE"

            echo "Finished agent steps for $REMOTE_HOSTNAME ($REMOTE_IP)"
          done

