# name: Deploy Zabbix Agent

# on: push

# jobs:
#   deploy_agent:
#     runs-on: self-hosted
#     steps:
#       - name: Set up Checkout
#         uses: actions/checkout@v4

#       - name: Welcome message
#         run: echo "My first Github Actions Job"

#       - name: List files
#         run: ls -l

#       - name: Read file
#         run: cat README.md

#       - name: Check directory
#         run: pwd

#     #   - name: Move File
#     #     run: cp deploy_agent.sh /home/ubuntu/

#     #   - name: Move Pem File
#     #     run: mv zbx_srv1.pem /home/ubuntu/zbx_srv1.pem       

#       - name: Execute the Script
#         run: bash -x deploy_zabbix_multi.sh

name: EC2 Script Deploy and OS Check

on: push

jobs:
  run_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (fetch PEM and script)
        uses: actions/checkout@v3

      - name: Secure PEM file
        run: chmod 600 zbx_srv1.pem

      - name: Run commands and deploy script on EC2
        env:
          REMOTE_IPS: ${{ secrets.REMOTE_IPS }}
          PEM_FILE: zbx_srv1.pem
          REMOTE_USER: ubuntu
          SCRIPT_LOCAL: zabbix_agent_add.sh
          SCRIPT_REMOTE: /home/ubuntu/zabbix_agent_add.sh
        run: |
          for REMOTE_IP in $(echo "$REMOTE_IPS" | tr ',' '\n'); do
            echo "--- $REMOTE_IP: OS Version ---"
            sudo ssh -o StrictHostKeyChecking=no -i "$PEM_FILE" "$REMOTE_USER@$REMOTE_IP" "cat /etc/os-release"

            echo "📦 Copying $SCRIPT_LOCAL to $REMOTE_USER@$REMOTE_IP ..."
            sudo scp -o StrictHostKeyChecking=no -i "$PEM_FILE" "$SCRIPT_LOCAL" "$REMOTE_USER@$REMOTE_IP:$SCRIPT_REMOTE"

            echo "🚀 Executing script on $REMOTE_USER@$REMOTE_IP ..."
            sudo ssh -o StrictHostKeyChecking=no -i "$PEM_FILE" "$REMOTE_USER@$REMOTE_IP" "bash $SCRIPT_REMOTE"
          done

